### ISSUE TITLE
Include stats page.

### ISSUE THREAD

**Issue by Qeolvdxu** [dnorhoj/AntiRickRoll#10]
@luis-1063 and I want to work on this issue to cross off the TODO list in the README.
We are think of adding total rolls you have been saved from, how many unique links have been rickrolls, ect.
If you could assign this issue to us that would be great ;)

**Comment by dnorhoj** [comment]
That sounds amazing! I'd probably also include a toggle.
Can't seem to add your friend tho, but i assigned it to you at least
