### ISSUE TITLE
Reminder: Mainfest v2 deprecation

### ISSUE THREAD

**Issue by Toad4707** [dnorhoj/AntiRickRoll#22]
Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.

 ],
  "name": "Rickroll Blocker",
  "version": "0.1.2",
  "description": "SAY GOODBYE!",
  **"manifest_version": 2,**
  "web_accessible_resources": [
    "warn/warn.html"
  ],
  "permissions": [
    "storage"

**Comment by dnorhoj** [comment]
https://github.com/dnorhoj/AntiRickRoll/blob/main/AntiRickRoll/manifest.json#L12
