### ISSUE TITLE
Still get rickroll'd...

### ISSUE THREAD

**Issue by Corne2Plum3** [dnorhoj/AntiRickRoll#7]
You forgot this one... https://www.youtube.com/watch?v=fcZXfoB2f70

Also you should add a list of all blocked site, and the possibilty to add rickroll lists.

**Comment by Theblockbuster1** [comment]
I just added this to https://antirickroll.theblock.heliohost.org and it should now get blocked (as long as you use the extension hosted on Github, as for now the latest version is not yet on the Chrome Web Store).
